language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - cp src/sgd/frontend/default_config.py src/sgd/frontend/config.py
script:
  - python setup.py install 
  - make tests
after_success:
  - coveralls

notifications:
  email:
    recipients:
      -yeastgenome.dev@gmail.com

