export const FETCH_DOWNLOADS_RESULTS_SUCCESS = 'FETCH_DOWNLOADS_RESULTS_SUCCESS';
export const FETCH_DOWNLOADS_MENU = 'FETCH_DOWNLOADS_MENU';
/*
export const SEARCH_RESPONSE = 'SEARCH_RESPONSE';
export const START_ASYNC_FETCH = 'START_ASYNC_FETCH';
export const ASYNC_SEARCH_RESPONSE = 'ASYNC_SEARCH_RESPONSE';
export const FINISH_ASYNC = 'FINISH_ASYNC';
export const SET_USER_INPUT = 'SET_USER_INPUT';
export const SEARCH_API_ERROR = 'SEARCH_API_ERROR';
export const HYDRATE_SEARCH = 'HYDRATE_SEARCH';
export const DEFAULT_STATE = 'DEFAULT_STATE';
export const START_SEARCH_FETCH = 'START_SEARCH_FETCH';
*/

